# Generated by Django 4.0.3 on 2022-04-08 20:55

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_cat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WackyWidgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(verbose_name=builtins.min)),
            ],
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
        migrations.DeleteModel(
            name='Toy',
        ),
    ]
